[main]2016-07-10 00:00:20,424 [WARN] - net.sf.ehcache.DiskStorePathManager.resolveAndLockIfNeeded(DiskStorePathManager.java:162):diskStorePath 'C:\Users\wengfj\AppData\Local\Temp' is already used by an existing CacheManager either in the same VM or in a different process.
The diskStore path for this CacheManager will be set to C:\Users\wengfj\AppData\Local\Temp\ehcache_auto_created1694042596848921151diskstore.
To avoid this warning consider using the CacheManager factory methods to create a singleton CacheManager or specifying a separate ehcache configuration (ehcache.xml) for each CacheManager instance.
[executionLogicHandlerThread+#-#-2]2016-07-10 00:22:06,522 [ERROR] - org.anyway.netty.socket.handler.SimpleDefaultHandler.exceptionCaught(SimpleDefaultHandler.java:38):[socket]Exception: 
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1098)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:112)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:544)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:399)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at java.lang.Thread.run(Thread.java:745)
[executionLogicHandlerThread+#-#-4]2016-07-10 00:22:06,526 [ERROR] - org.anyway.netty.socket.handler.SimpleDefaultHandler.exceptionCaught(SimpleDefaultHandler.java:38):[socket]Exception: 
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1098)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:112)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:544)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:399)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at java.lang.Thread.run(Thread.java:745)
[executionLogicHandlerThread+#-#-3]2016-07-10 00:22:06,526 [ERROR] - org.anyway.netty.socket.handler.SimpleDefaultHandler.exceptionCaught(SimpleDefaultHandler.java:38):[socket]Exception: 
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1098)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:112)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:544)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:399)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at java.lang.Thread.run(Thread.java:745)
[executionLogicHandlerThread+#-#-1]2016-07-10 00:22:06,525 [ERROR] - org.anyway.netty.socket.handler.SimpleDefaultHandler.exceptionCaught(SimpleDefaultHandler.java:38):[socket]Exception: 
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1098)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:112)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:544)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:399)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at java.lang.Thread.run(Thread.java:745)
[main]2016-07-10 00:29:33,959 [WARN] - net.sf.ehcache.DiskStorePathManager.resolveAndLockIfNeeded(DiskStorePathManager.java:162):diskStorePath 'C:\Users\wengfj\AppData\Local\Temp' is already used by an existing CacheManager either in the same VM or in a different process.
The diskStore path for this CacheManager will be set to C:\Users\wengfj\AppData\Local\Temp\ehcache_auto_created4568930301174426644diskstore.
To avoid this warning consider using the CacheManager factory methods to create a singleton CacheManager or specifying a separate ehcache configuration (ehcache.xml) for each CacheManager instance.
[qtp1562157875-25]2016-07-10 17:53:52,490 [WARN] - org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:358):ERROR_DISPATCH loop detected on Request[POST //127.0.0.1:9091/]@2dc8fe96 {}
[qtp1562157875-25]2016-07-10 17:53:52,507 [WARN] - org.eclipse.jetty.server.HttpChannel.handleException(HttpChannel.java:520):Error while handling async error: 
java.util.concurrent.TimeoutException: Async API violation
	at org.eclipse.jetty.server.HttpChannelState.onTimeout(HttpChannelState.java:532)
	at org.eclipse.jetty.server.AsyncContextEvent.run(AsyncContextEvent.java:161)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	Suppressed: org.eclipse.jetty.io.EofException
		at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:197)
		at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:420)
		at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:313)
		at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:140)
		at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:733)
		at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
		at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
		at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:521)
		at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:692)
		at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:746)
		at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:179)
		at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:163)
		at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:441)
		at org.eclipse.jetty.util.ByteArrayISO8859Writer.writeTo(ByteArrayISO8859Writer.java:109)
		at org.eclipse.jetty.server.Response.sendError(Response.java:609)
		at org.eclipse.jetty.server.Response.sendError(Response.java:515)
		at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:361)
		at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:266)
		at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
		at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
		... 1 more
	Caused by: java.io.IOException: 你的主机中的软件中止了一个已建立的连接。
		at sun.nio.ch.SocketDispatcher.writev0(Native Method)
		at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:55)
		at sun.nio.ch.IOUtil.write(IOUtil.java:148)
		at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504)
		at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:177)
		... 20 more
[qtp1562157875-32]2016-07-10 18:00:29,574 [WARN] - org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:358):ERROR_DISPATCH loop detected on Request[POST //127.0.0.1:9091/]@4f5a160c {}
[qtp1562157875-32]2016-07-10 18:00:29,576 [WARN] - org.eclipse.jetty.server.HttpChannel.handleException(HttpChannel.java:520):Error while handling async error: 
java.util.concurrent.TimeoutException: Async API violation
	at org.eclipse.jetty.server.HttpChannelState.onTimeout(HttpChannelState.java:532)
	at org.eclipse.jetty.server.AsyncContextEvent.run(AsyncContextEvent.java:161)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	Suppressed: org.eclipse.jetty.io.EofException
		at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:197)
		at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:420)
		at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:313)
		at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:140)
		at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:733)
		at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
		at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
		at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:521)
		at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:692)
		at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:746)
		at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:179)
		at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:163)
		at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:441)
		at org.eclipse.jetty.util.ByteArrayISO8859Writer.writeTo(ByteArrayISO8859Writer.java:109)
		at org.eclipse.jetty.server.Response.sendError(Response.java:609)
		at org.eclipse.jetty.server.Response.sendError(Response.java:515)
		at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:361)
		at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:266)
		at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
		at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
		... 1 more
	Caused by: java.io.IOException: 你的主机中的软件中止了一个已建立的连接。
		at sun.nio.ch.SocketDispatcher.writev0(Native Method)
		at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:55)
		at sun.nio.ch.IOUtil.write(IOUtil.java:148)
		at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504)
		at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:177)
		... 20 more
